# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 13:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0009_add_incicent_permissions'),
        ('fir_artifacts', '0005_delete_artifactwhitelistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('investigation', 'Investigation'), ('alerting', 'Alerting'), ('countermeasure', 'Countermeasure'), ('other', 'Other')], max_length=20, verbose_name='type')),
                ('subject', models.CharField(max_length=256, verbose_name='subject')),
                ('description', models.TextField(verbose_name='description')),
                ('state', django_fsm.FSMField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('blocked', 'Blocked'), ('closed', 'Closed')], default='created', max_length=50, protected=True)),
                ('auto_state', models.BooleanField(default=False)),
                ('business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.BusinessLine')),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.Incident')),
            ],
            options={
                'verbose_name': 'action',
            },
        ),
        migrations.CreateModel(
            name='ActionComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comment', models.TextField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_actions.Action')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=100, verbose_name='what')),
                ('state', django_fsm.FSMField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('refused', 'Refused'), ('enforced', 'Enforced'), ('blocked', 'Blocked'), ('deletion_proposed', 'Deletion proposed'), ('deletion_approved', 'Deletion approved'), ('deleted', 'Deleted')], default='proposed', max_length=50, protected=True)),
                ('comment', models.TextField(blank=True, null=True, verbose_name='comment')),
                ('actions', models.ManyToManyField(blank=True, related_name='blocks', to='fir_actions.Action', verbose_name='actions')),
                ('artifacts', models.ManyToManyField(related_name='blocks', to='fir_artifacts.Artifact')),
            ],
            options={
                'permissions': (('can_approve_block', 'Can approve block'), ('can_propose_block', 'Can propose block'), ('can_enforce_block', 'Can enforce block')),
            },
        ),
        migrations.CreateModel(
            name='BlockLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69, verbose_name='name')),
                ('business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.BusinessLine')),
            ],
        ),
        migrations.CreateModel(
            name='BlockType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=69, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='blocklocation',
            name='types',
            field=models.ManyToManyField(related_name='locations', to='fir_actions.BlockType', verbose_name='types'),
        ),
        migrations.AddField(
            model_name='block',
            name='how',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='fir_actions.BlockType', verbose_name='how'),
        ),
        migrations.AddField(
            model_name='block',
            name='incidents',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='incidents.Incident', verbose_name='incidents'),
        ),
        migrations.AddField(
            model_name='block',
            name='where',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='fir_actions.BlockLocation', verbose_name='where'),
        ),
    ]
