# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 20:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fir_actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='opened_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='action',
            name='opened_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='action',
            name='business_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.BusinessLine'),
        ),
        migrations.AlterField(
            model_name='action',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.Incident'),
        ),
        migrations.AlterField(
            model_name='actioncomment',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='fir_actions.Action'),
        ),
    ]
