# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 18:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0009_add_incicent_permissions'),
        ('fir_actions', '0002_auto_20160916_2007'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('business_lines', models.ManyToManyField(blank=True, to='incidents.BusinessLine', verbose_name='business lines')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.IncidentCategory', verbose_name='category')),
                ('detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.Label', verbose_name='detection')),
            ],
            options={
                'verbose_name': 'action template list',
                'verbose_name_plural': 'action template list',
            },
        ),
        migrations.CreateModel(
            name='ActionTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('investigation', 'Investigation'), ('alerting', 'Alerting'), ('countermeasure', 'Countermeasure'), ('other', 'Other')], max_length=20, verbose_name='type')),
                ('subject', models.CharField(max_length=256, verbose_name='subject')),
                ('description', models.TextField(verbose_name='description')),
                ('business_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_templates', to='incidents.BusinessLine')),
            ],
            options={
                'verbose_name': 'action template',
                'verbose_name_plural': 'action templates',
            },
        ),
        migrations.AlterModelOptions(
            name='block',
            options={'permissions': (('can_approve_block', 'Can approve block'), ('can_enforce_block', 'Can enforce block'))},
        ),
        migrations.RemoveField(
            model_name='block',
            name='artifacts',
        ),
    ]
