# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_actions', '0003_auto_20160920_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlist',
            name='actions',
            field=models.ManyToManyField(to='fir_actions.ActionTemplate', verbose_name='actions'),
        ),
    ]
