# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-22 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_artifacts', '0005_delete_artifactwhitelistitem'),
        ('fir_actions', '0004_actionlist_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='artifacts',
            field=models.ManyToManyField(related_name='blocks', to='fir_artifacts.Artifact'),
        ),
    ]
