# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-12 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_actions', '0006_auto_20161012_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontemplate',
            name='description',
            field=models.TextField(help_text='You can use Django template language here.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='subject',
            field=models.CharField(help_text='You can use Django template language here.', max_length=256, verbose_name='subject'),
        ),
    ]
