# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-13 17:35
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('fir_actions', '0007_auto_20161012_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'permissions': (('can_approve_block', 'Can approve block'), ('can_enforce_block', 'Can enforce block')), 'verbose_name': 'block'},
        ),
        migrations.AlterModelOptions(
            name='blocklocation',
            options={'verbose_name': 'block location', 'verbose_name_plural': 'block locations'},
        ),
        migrations.AlterModelOptions(
            name='blocktype',
            options={'verbose_name': 'block type', 'verbose_name_plural': 'block types'},
        ),
        migrations.AlterField(
            model_name='action',
            name='auto_state',
            field=models.BooleanField(default=False, verbose_name='auto state'),
        ),
        migrations.AlterField(
            model_name='action',
            name='business_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.BusinessLine', verbose_name='business line'),
        ),
        migrations.AlterField(
            model_name='action',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='incidents.Incident', verbose_name='incident'),
        ),
        migrations.AlterField(
            model_name='action',
            name='opened_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creator'),
        ),
        migrations.AlterField(
            model_name='action',
            name='opened_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='action',
            name='state',
            field=django_fsm.FSMField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('blocked', 'Blocked'), ('closed', 'Closed')], default='created', max_length=50, protected=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='actiontemplate',
            name='business_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='action_templates', to='incidents.BusinessLine', verbose_name='business line'),
        ),
        migrations.AlterField(
            model_name='block',
            name='state',
            field=django_fsm.FSMField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('refused', 'Refused'), ('enforced', 'Enforced'), ('blocked', 'Blocked'), ('deletion_proposed', 'Deletion proposed'), ('deletion_approved', 'Deletion approved'), ('deleted', 'Deleted')], default='proposed', max_length=50, protected=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='blocklocation',
            name='business_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='incidents.BusinessLine', verbose_name='business line'),
        ),
    ]
